
library(readr)
library(lubridate)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(openair)
library(stringr)
library(plyr)
acreditado<-read.csv("C:/Users/Rafael B/Documents/laboratorios_acreditados.csv")
acreditado2<-read.csv("C:/Users/Rafael B/Documents/LISTADO MATRIZ AIRE.csv")
sum(str_count(acreditado$Componente,pattern="Calidaddeaire"))
sum(str_count(acreditado$Componente,pattern="FuentesFijas"))
unique(acreditado$NombredelLaboratorio)
doble_acreditacion<-acreditado$NombredelLaboratorio[duplicated(acreditado$NombredelLaboratorio)]
doble_acreditacion1<-acreditado[duplicated(acreditado$NombredelLaboratorio),]
doble_acreditacion2<-acreditado[doble_acreditacion1$NombredelLaboratorio==acreditado$NombredelLaboratorio,]
dacr<-rbind(doble_acreditacion1,doble_acreditacion2)
sum(str_count(acreditado$Actividad))
unique(acreditado$Ciudad)
col<-c("black","dodgerblue","firebrick1","chartreuse3",
"deeppink","darkorchid3","darkorange1","bisque","darkgray","darkorchid","#13FF00",
"cadetblue2","burlywood","darkgoldenrod1","darkolivegreen1","lightgrey",
"darkkhaki","deepskyblue2","darkorange4","darkslateblue","chocolate3","indianred1",
"khaki","lavender")
freq<-count(acreditado,"Variable")
freq$Variable<-c("C6H6","Br-","DPTPRMYVDF","SO2","NO2","PM2.5","PM","PM10","CO","STP")
ggplot(freq,aes(x=Variable,y=freq))+geom_bar(stat="identity")
ggplot(acreditado,aes(Componente,fill=Ciudad))+geom_bar(position=position_dodge())+theme_minimal()
acreditado$Componente<-str_replace_all(acreditado$Componente,"CalidaddeAire","Calidaddeaire")
caff<-count(acreditado,"Componente")
ciudad<-count(acreditado,"Ciudad")
ggplot(acreditado,aes(Componente,fill=Ciudad))+geom_bar(position=position_dodge())+theme_minimal()+scale_fill_manual(values=col)+ylab("laboratoriosacreditados")
leyigual<-acreditado[duplicated(acreditado$Actos.administrativos.que.soportan.el.alcance),]
acreditado$Variable<-str_replace_all(acreditado$Variable,"MaterialParticuladoMenora10micras","PM10")
acreditado$Variable<-str_replace_all(acreditado$Variable,"MaterialParticuladoMenora2.5micras","PM2.5")
acreditado$Variable<-str_replace_all(acreditado$Variable,"ParticulasSuspendidasTotales","PST")
acreditado$Variable<-str_replace_all(acreditado$Variable,"DioxidodeAzufre","SO2")
acreditado$Variable<-str_replace_all(acreditado$Variable,"DeterminaciondePuntosTransversosparaRealizarMuestreoyVelocidadenFuentesEstacionarias","DPTRMVFE")
acreditado$Variable<-str_replace_all(acreditado$Variable,"DioxidodeNitrogeno","NO2")
acreditado$Variable<-str_replace_all(acreditado$Variable,"MonoxidodeCarbono","CO")
acreditado$Variable<-str_replace_all(acreditado$Variable,"Bromuro","Br-")
acreditado$Variable<-str_replace_all(acreditado$Variable,"Benceno","C6H6")
acreditado$Actividad<-str_replace_all(acreditado$Actividad,"Determinacion","determinacion")
colnames(acreditado)=c("codigo","acreditacion","matriz","componente","actividad","grupo","variable","tecnica","metodo","intervalo_med_dir","nom_est","direccion","latitud","longitud","idequipo","nombre_lab","NIT","contacto","ciudad","departamento","direccion2","telefono","correo","actos","desde","hasta","acogimiento")
freqdacr<-count(dacr,"NombredelLaboratorio")
freqdacr=freqdacr[-1,]
freqdacr$conv<-2:length(freqdacr$freq)
count(acreditado,"metodo")
ggplot(freqdacr,aes(Seleccionelasactividadesquesuorganizaciónrealiza,fill=Microbalanza..6.cifras.decimales.))+geom_bar(position=position_dodge())+theme_minimal()+scale_fill_manual(values=col)+ylab("laboratoriosacreditados")
ggplot(acreditado2,aes(x="",y=Codigodelaboratorio,fill=Matriz))+geom_bar(stat="identity")+coord_polar("y")

unique(filter(acreditado2,Componente=="Agua")$Matriz)
ggplot(acreditado2,aes(x="",y=Codigodelaboratorio,fill=Matriz))+geom_bar(stat="identity")+coord_polar("y")+scale_fill_manual(values=col)
acreditado2$Matriz<-str_replace_all(acreditado2$Matriz,"BiosÑlido","Biosolido")
acreditado2$Matriz<-str_replace_all(acreditado2$Matriz,"AceiteDiel?ctrico","AceiteDielectrico")
label<-count(acreditado2$Matriz)
label$perc<-label$freq/sum(label$freq)*100
label$perc<-round(label$perc,digits=2)
label$x[1]<-"AceiteDielectrico"
ggplot(label,aes(x="",y=freq,fill=x))+geom_bar(stat="identity")+coord_polar("y")+scale_fill_manual(values=col)+ylab("Laboratorios")+geom_label(aes(label=perc))
tecnica_agua<-count(filter(acreditado2,Componente=="Agua")$Tcnica)
grupo_agua<-count(filter(acreditado2,Componente=="Agua")$Grupo)
grupo_agua<-grupo_agua[-1,]
grupo_agua$perc<-grupo_agua$freq/sum(grupo_agua$freq)*100
grupo_agua$perc<-round(grupo_agua$perc,digits=2)
tecnica_agua<-tecnica_agua[-1,]
tecnica_agua$perc<-tecnica_agua$freq/sum(tecnica_agua$freq)*100
tecnica_agua$perc<-round(tecnica_agua$perc,digits=2)
ggplot(label,aes(x="",y=freq,fill=x))+geom_col() +geom_label(aes(label = perc),position = position_stack(vjust = 0.5),show.legend = FALSE) + coord_polar(theta = "y")+ylab("Laboratorios")+scale_fill_manual(values=col)